
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Green Earth Drive", "Environment", 100, "3/17/20", "3/17/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("For the Pupperinos", "Animals", 200, "1/15/20", "1/15/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cookies for the Homeless", "Homeless", 150, "2/17/20", "2/17/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Books for Kids", "Kids", 250, "1/21/20", "1/21/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Stop Loneliness", "Elderly", 300, "2/11/20", "2/21/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Building Houses for Less Fortunate", "Homeless", 150, "6/20/19", "6/20/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Donuts for Depression", "Mental Health", 1000, "11/11/20", "11/11/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Urban Cleanup", "Environment", 50, "7/04/20", "7/04/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Connecting through Pain", "Addiction", 400, "6/25/20", "6/25/21");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Cleanup the Streets", "Crime", 700, "9/22/20", "9/22/21");

INSERT INTO users (name, age) VALUES ("James Johnson", 32);
INSERT INTO users (name, age) VALUES ("Karl Mather", 21);
INSERT INTO users (name, age) VALUES ("Rhiannon James", 42);
INSERT INTO users (name, age) VALUES ("Seth Cones", 15);
INSERT INTO users (name, age) VALUES ("Mike Obrien", 10);
INSERT INTO users (name, age) VALUES ("Heather Steck", 53);
INSERT INTO users (name, age) VALUES ("Sara Davik", 42);
INSERT INTO users (name, age) VALUES ("Patrick Fossen", 26);
INSERT INTO users (name, age) VALUES ("Justin Gicho", 39);
INSERT INTO users (name, age) VALUES ("Carrier Jones", 17);
INSERT INTO users (name, age) VALUES ("Lil Peep", 19);
INSERT INTO users (name, age) VALUES ("Lil Wayne", 38);
INSERT INTO users (name, age) VALUES ("Brooke Kreber", 43);
INSERT INTO users (name, age) VALUES ("Nancy Gregory", 84);
INSERT INTO users (name, age) VALUES ("Mike Fynaz", 62);
INSERT INTO users (name, age) VALUES ("Frank Pelzl", 63);
INSERT INTO users (name, age) VALUES ("Jessie Narki", 11);
INSERT INTO users (name, age) VALUES ("Lebron Noni", 28);
INSERT INTO users (name, age) VALUES ("Matt Warrem", 25);
INSERT INTO users (name, age) VALUES ("Topaz Hayes", 97);

INSERT INTO pledges (amount, user_id, project_id) VALUES (40,1,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40,1,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75,2,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75,2,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75,2,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200,3,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25,4,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25,4,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30,5,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30,5,10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30,5,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75,6,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75,6,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,7,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,7,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100,7,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (37,8,6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200,9,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15,10,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15,20,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15,10,5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20,11,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20,19,7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (150,12,1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (125,13,9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (175,14,8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75,15,3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25,16,4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50,17,2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1000,18,5);
