INSERT INTO Projects (title, funding_goal) VALUES ("Animal shelter need dog food", 210);
INSERT INTO Projects (title) VALUES ("Help me buy a guitar");
INSERT INTO Projects (title) VALUES ("Help save birds of paradize");
INSERT INTO Projects (title) VALUES ("I have bed bugs!");
INSERT INTO Projects (title) VALUES ("I want to teach English in China");
INSERT INTO Projects (title) VALUES ("Iguana needs tail operation");
INSERT INTO Projects (title) VALUES ("My book on SQL");
INSERT INTO Projects (title) VALUES ("The next Harry Potter");
INSERT INTO Projects (title) VALUES ("The next Inna-Gagga-Davida");
INSERT INTO Projects (title) VALUES ("Voldement needs a body");

INSERT INTO Users (name, age) VALUES ("Albus", 113);
INSERT INTO Users (name, age) VALUES ("Alex", 33);
INSERT INTO Users (name, age) VALUES ("Amanda", 24);
INSERT INTO Users (name, age) VALUES ("Bear", 6);
INSERT INTO Users (name, age) VALUES ("Ena", 24);
INSERT INTO Users (name, age) VALUES ("Finnebar", 17);
INSERT INTO Users (name, age) VALUES ("Franz", 100);
INSERT INTO Users (name, age) VALUES ("Hermione", 30);
INSERT INTO Users (name, age) VALUES ("Iguana", 4);
INSERT INTO Users (name, age) VALUES ("Katie", 24);
INSERT INTO Users (name, age) VALUES ("Marisa", 24);
INSERT INTO Users (name, age) VALUES ("Pacha", 5);
INSERT INTO Users (name, age) VALUES ("Rosey", 9);
INSERT INTO Users (name, age) VALUES ("Sirius", 36);
INSERT INTO Users (name, age) VALUES ("Sophie", 24);
INSERT INTO Users (name, age) VALUES ("Squid", 5);
INSERT INTO Users (name, age) VALUES ("Swizzle", 4);
INSERT INTO Users (name, age) VALUES ("Victoria", 23);
INSERT INTO Users (name, age) VALUES ("Voldemort", 90);
INSERT INTO Users (name, age) VALUES ("Whale", 6);

INSERT INTO Pledges (amount) VALUES (470);
INSERT INTO Pledges (amount) VALUES (20);
INSERT INTO Pledges (amount) VALUES (40);
INSERT INTO Pledges (amount) VALUES (50);
INSERT INTO Pledges (amount) VALUES (100);
INSERT INTO Pledges (amount) VALUES (70);
INSERT INTO Pledges (amount) VALUES (90);
INSERT INTO Pledges (amount) VALUES (50);
INSERT INTO Pledges (amount) VALUES (10);
INSERT INTO Pledges (amount) VALUES (170);
INSERT INTO Pledges (amount) VALUES (24);
INSERT INTO Pledges (amount) VALUES (60);
INSERT INTO Pledges (amount) VALUES (50);
INSERT INTO Pledges (amount) VALUES (19);
INSERT INTO Pledges (amount) VALUES (60);
INSERT INTO Pledges (amount) VALUES (270);
INSERT INTO Pledges (amount) VALUES (12);
INSERT INTO Pledges (amount) VALUES (1700);
INSERT INTO Pledges (amount) VALUES (34);
INSERT INTO Pledges (amount) VALUES (125.5);
INSERT INTO Pledges (amount) VALUES (470);
INSERT INTO Pledges (amount) VALUES (470);
INSERT INTO Pledges (amount) VALUES (470);
INSERT INTO Pledges (amount) VALUES (470);
INSERT INTO Pledges (amount) VALUES (470);
INSERT INTO Pledges (amount) VALUES (470);
INSERT INTO Pledges (amount) VALUES (470);
INSERT INTO Pledges (amount) VALUES (470);
INSERT INTO Pledges (amount) VALUES (470);
INSERT INTO Pledges (amount) VALUES (470);