INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p1", "c1", 1000000, "13/10/2020", "20/11/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p2", "c2", 5000, "20/11/2020", "07/01/2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p3", "c1", 3500000, "10/12/2020", "31/12/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p4", "c3", 2000000, "08/07/2020", "09/09/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p5", "c3", 750000, "29/11/2020", "01/02/2021");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p6", "c1", 8000, "31/07/2020", "31/09/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p7", "c2", 99999, "09/09/2020", "24/11/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p8", "c2", 325000, "02/12/2020", "02/01/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p9", "c3", 25000, "03/04/2020", "04/05/2020");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("p10", "c1", 10000000, "09/11/2020", "01/01/2020");

INSERT INTO users (name, age) VALUES ("Uri", 37);
INSERT INTO users (name, age) VALUES ("Giselda", 29);
INSERT INTO users (name, age) VALUES ("Fela", 43);
INSERT INTO users (name, age) VALUES ("Wendell", 54);
INSERT INTO users (name, age) VALUES ("Jay", 18);
INSERT INTO users (name, age) VALUES ("Yuri", 71);
INSERT INTO users (name, age) VALUES ("Noella", 27);
INSERT INTO users (name, age) VALUES ("Keisha", 30);
INSERT INTO users (name, age) VALUES ("Rafa", 34);
INSERT INTO users (name, age) VALUES ("Jin", 32);
INSERT INTO users (name, age) VALUES ("Yukiko", 33);
INSERT INTO users (name, age) VALUES ("Zelda", 22);
INSERT INTO users (name, age) VALUES ("Link", 17);
INSERT INTO users (name, age) VALUES ("Ratchet", 24);
INSERT INTO users (name, age) VALUES ("Indigo", 42);
INSERT INTO users (name, age) VALUES ("Kelvin", 24);
INSERT INTO users (name, age) VALUES ("Raury", 44);
INSERT INTO users (name, age) VALUES ("Buffalo", 82);
INSERT INTO users (name, age) VALUES ("Quincy", 64);
INSERT INTO users (name, age) VALUES ("Leila", 29);

INSERT INTO pledges (amount, project_id, user_id) VALUES (30, 1, 19);
INSERT INTO pledges (amount, project_id, user_id) VALUES (300, 2, 20);
INSERT INTO pledges (amount, project_id, user_id) VALUES (45, 6, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 5, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (99, 8, 2);
INSERT INTO pledges (amount, project_id, user_id) VALUES (450, 8, 3);
INSERT INTO pledges (amount, project_id, user_id) VALUES (200, 9, 18);
INSERT INTO pledges (amount, project_id, user_id) VALUES (25, 10, 11);
INSERT INTO pledges (amount, project_id, user_id) VALUES (65, 2, 17);
INSERT INTO pledges (amount, project_id, user_id) VALUES (80, 3, 16);
INSERT INTO pledges (amount, project_id, user_id) VALUES (250, 4, 12);
INSERT INTO pledges (amount, project_id, user_id) VALUES (45, 2, 9);
INSERT INTO pledges (amount, project_id, user_id) VALUES (39, 7, 8);
INSERT INTO pledges (amount, project_id, user_id) VALUES (600, 7, 5);
INSERT INTO pledges (amount, project_id, user_id) VALUES (5, 8, 4);
INSERT INTO pledges (amount, project_id, user_id) VALUES (92, 9, 6);
INSERT INTO pledges (amount, project_id, user_id) VALUES (40, 10, 17);
INSERT INTO pledges (amount, project_id, user_id) VALUES (33, 2, 10);
INSERT INTO pledges (amount, project_id, user_id) VALUES (67, 4, 13);
INSERT INTO pledges (amount, project_id, user_id) VALUES (987, 5, 14);
INSERT INTO pledges (amount, project_id, user_id) VALUES (1050, 6, 17);
INSERT INTO pledges (amount, project_id, user_id) VALUES (678, 8, 3);
INSERT INTO pledges (amount, project_id, user_id) VALUES (403, 9, 15);
INSERT INTO pledges (amount, project_id, user_id) VALUES (402, 10, 16);
INSERT INTO pledges (amount, project_id, user_id) VALUES (204, 1, 16);
INSERT INTO pledges (amount, project_id, user_id) VALUES (20, 2, 16);
INSERT INTO pledges (amount, project_id, user_id) VALUES (40, 4, 1);
INSERT INTO pledges (amount, project_id, user_id) VALUES (10, 3, 4);
INSERT INTO pledges (amount, project_id, user_id) VALUES (15, 5, 3);
INSERT INTO pledges (amount, project_id, user_id) VALUES (5000, 6, 8);